parameters:
- name: dependsOn
  type: object
  default: []
- name: azureSubscription
  type: string
- name: environment
  type: string
- name: environmentName
  type: string
- name: environmentTag
  type: string

jobs:
- deployment: ValidateBicepAgainst${{ parameters.environmentName }}Environment
  dependsOn: ${{ parameters.dependsOn }}
  environment: ${{ parameters.environment }}

  workspace:
    clean: all

  strategy:
    runOnce:
      deploy:
        steps:
          - checkout: self

          - task: AzureCLI@2
            name: RunPreflightValidation
            inputs:
              azureSubscription: ${{ parameters.azureSubscription }}
              scriptType: 'pscore'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az deployment sub validate `
                  --name 'strategicKeyVault${{ parameters.environmentName }}' `
                  --template-file bicep/platformKeyVault.bicep `
                  --location 'uksouth' `
                  --parameters @params/platformKeyVault.${{ parameters.environmentTag }}.json `
                      parPlatformKeyVaultCreateMode='recover'

                if ($null -eq (az keyvault show --name 'kv-mx-pltfrm-${{ parameters.environmentTag }}-uksouth')) { $skipBicepValidate = $true }

                if ($skipBicepValidate -ne $true) { 
                  az deployment sub validate `
                    --name 'strategicPlatform${{ parameters.environmentName }}' `
                    --template-file bicep/platform.bicep `
                    --location 'uksouth' `
                    --parameters @params/platform.${{ parameters.environmentTag }}.json `
                      parSqlAdminOid='00000000-0000-0000-0000-000000000000'
                }

          - task: AzureCLI@2
            name: RunWhatIfDeploy
            inputs:
              azureSubscription: ${{ parameters.azureSubscription }}
              scriptType: 'pscore'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az deployment sub what-if `
                  --name 'strategicKeyVault${{ parameters.environmentName }}' `
                  --template-file bicep/platformKeyVault.bicep `
                  --location 'uksouth' `
                  --parameters @params/platformKeyVault.${{ parameters.environmentTag }}.json `
                      parPlatformKeyVaultCreateMode='recover'

                if ($null -eq (az keyvault show --name 'kv-mx-pltfrm-${{ parameters.environmentTag }}-uksouth')) { $skipBicepValidate = $true }
                
                if ($skipBicepValidate -ne $true) { 
                  az deployment sub what-if `
                    --name 'strategicPlatform${{ parameters.environmentName }}' `
                    --template-file bicep/platform.bicep `
                    --location 'uksouth' `
                    --parameters @params/platform.${{ parameters.environmentTag }}.json `
                      parSqlAdminOid='00000000-0000-0000-0000-000000000000'
                }
