parameters:
- name: jobName
  type: string
  default: BicepEnvironmentValidation
- name: dependsOn
  type: object
  default: []
- name: azureSubscription
  type: string
- name: environment
  type: string

jobs:
- deployment: ${{ parameters.jobName }}
  dependsOn: ${{ parameters.dependsOn }}
  environment: 'platform-strategic-services-${{ parameters.environment }}'

  workspace:
    clean: all

  strategy:
    runOnce:
      deploy:
        steps:
          - checkout: self

          - task: AzureCLI@2
            name: RunPreflightValidation
            inputs:
              azureSubscription: ${{ parameters.azureSubscription }}
              scriptType: 'pscore'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az deployment sub validate `
                  --template-file bicep/platformKeyVault.bicep `
                  --location 'uksouth' `
                  --parameters @params/platformKeyVault.${{ parameters.environment }}.json `
                      parPlatformKeyVaultCreateMode='recover' `
                      parNugetKeyVaultCreateMode='recover'

                if (($null -ne (az keyvault show --name 'kv-mx-pltfrm-${{ parameters.environment }}-uksouth')) -and ($null -ne (az keyvault show --name 'kv-mx-nuget-${{ parameters.environment }}-uksouth'))) { 
                  az deployment sub validate `
                    --template-file bicep/platform.bicep `
                    --location 'uksouth' `
                    --parameters @params/platform.${{ parameters.environment }}.json `
                      parSqlAdminOid='00000000-0000-0000-0000-000000000000'
                }

          - task: AzureCLI@2
            name: RunWhatIfDeploy
            inputs:
              azureSubscription: ${{ parameters.azureSubscription }}
              scriptType: 'pscore'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az deployment sub what-if `
                  --template-file bicep/platformKeyVault.bicep `
                  --location 'uksouth' `
                  --parameters @params/platformKeyVault.${{ parameters.environment }}.json `
                      parPlatformKeyVaultCreateMode='recover' `
                      parNugetKeyVaultCreateMode='recover'

                if (($null -ne (az keyvault show --name 'kv-mx-pltfrm-${{ parameters.environment }}-uksouth')) -and ($null -ne (az keyvault show --name 'kv-mx-nuget-${{ parameters.environment }}-uksouth'))) { 
                  az deployment sub what-if `
                    --template-file bicep/platform.bicep `
                    --location 'uksouth' `
                    --parameters @params/platform.${{ parameters.environment }}.json `
                      parSqlAdminOid='00000000-0000-0000-0000-000000000000'
                }
