trigger: none
pr: none

pool: 'Dedicated'

resources:
  pipelines:
  - pipeline: platform-strategic-services.Validate
    source: platform-strategic-services.Validate
    trigger:
      branches:
        include:
        - main

stages: 
- stage: DeployDevPlatform
  jobs:

  - deployment: DeployDevPlatformKeyVaultBicep
    environment: 'platform-strategic-services-dev'

    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self

            - task: AzureCLI@2
              displayName: DeployDevPlatformKeyVaultBicep
              inputs:
                azureSubscription: 'spn-ado-Personal-Public-devtest'
                scriptType: 'pscore'
                scriptLocation: 'inlineScript'
                inlineScript: |
                    if ($null -eq (az keyvault show --name 'kv-mx-pltfrm-dev-uksouth')) { $platformKeyVaultCreateMode = 'default' } else { $platformKeyVaultCreateMode = 'recover' }
                    if ($null -eq (az keyvault show --name 'kv-mx-nuget-dev-uksouth')) { $nugetKeyVaultCreateMode = 'default' } else { $nugetKeyVaultCreateMode = 'recover' }

                    az deployment sub create `
                      --template-file bicep/platformKeyVault.bicep `
                      --location 'uksouth' `
                      --parameters @params/platformKeyVault.dev.json `
                        parPlatformKeyVaultCreateMode=$platformKeyVaultCreateMode `
                        parNugetKeyVaultCreateMode=$nugetKeyVaultCreateMode

            - task: AzureCLI@2
              displayName: SetSqlServerAdminCredentials
              inputs:
                azureSubscription: 'spn-ado-Personal-Public-devtest'
                scriptType: 'pscore'
                scriptLocation: 'scriptPath'
                arguments: '"dev" "uksouth"'
                addSpnToEnvironment: true
                scriptPath: '$(Build.sourcesDirectory)/.azure-pipelines/scripts/SetSqlServerAdminCredentials.ps1'

            - task: AzureCLI@2
              displayName: CreateDatabaseAADGroups
              inputs:
                azureSubscription: 'spn-ado-Personal-Public-devtest'
                scriptType: 'pscore'
                scriptLocation: 'scriptPath'
                arguments: '"dev"'
                addSpnToEnvironment: true
                scriptPath: '$(Build.sourcesDirectory)/.azure-pipelines/scripts/CreateDatabaseAADGroups.ps1'

  - deployment: DeployDevPlatformBicep
    dependsOn: [DeployDevPlatformKeyVaultBicep]
    environment: 'platform-strategic-services'

    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self
            
            - task: AzureCLI@2
              displayName: DeployDevPlatformBicep
              inputs:
                azureSubscription: 'spn-ado-Personal-Public-devtest'
                scriptType: 'pscore'
                scriptLocation: 'inlineScript'
                inlineScript: |
                  $sqlAdminOid = (az ad group show --group "sg-sql-platform-dev-admins" --query 'id')  | ConvertFrom-Json

                  az deployment sub create `
                    --template-file bicep/platform.bicep `
                    --location 'uksouth' `
                    --parameters @params/platform.dev.json `
                      parSqlAdminOid=$sqlAdminOid

  - job: DeployDevPlatformPermissions
    dependsOn: [DeployDevPlatformBicep]
    steps:
      - task: AzureCLI@2
        displayName: CreateSqlServerRoleAssignment
        inputs:
          azureSubscription: 'spn-ado-Personal-Public-devtest'
          scriptType: 'pscore'
          scriptLocation: 'scriptPath'
          arguments: '"sql-platform-dev-uksouth" "rg-platform-sql-dev-uksouth"'
          scriptPath: '$(Build.sourcesDirectory)/.azure-pipelines/scripts/CreateSqlServerRoleAssignment.ps1'

- stage: DeployPrdPlatform
  jobs:

  - deployment: DeployPrdPlatformKeyVaultBicep
    environment: 'platform-strategic-services'

    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self

            - task: AzureCLI@2
              displayName: DeployPrdPlatformKeyVaultBicep
              inputs:
                azureSubscription: 'spn-ado-Personal-Public-strategic-prd'
                scriptType: 'pscore'
                scriptLocation: 'inlineScript'
                inlineScript: |
                    if ($null -eq (az keyvault show --name 'kv-mx-pltfrm-prd-uksouth')) { $platformKeyVaultCreateMode = 'default' } else { $platformKeyVaultCreateMode = 'recover' }
                    if ($null -eq (az keyvault show --name 'kv-mx-nuget-prd-uksouth')) { $nugetKeyVaultCreateMode = 'default' } else { $nugetKeyVaultCreateMode = 'recover' }

                    az deployment sub create `
                      --template-file bicep/platformKeyVault.bicep `
                      --location 'uksouth' `
                      --parameters @params/platformKeyVault.prd.json `
                        parPlatformKeyVaultCreateMode=$platformKeyVaultCreateMode `
                        parNugetKeyVaultCreateMode=$nugetKeyVaultCreateMode

            - task: AzureCLI@2
              displayName: SetSqlServerAdminCredentials
              inputs:
                azureSubscription: 'spn-ado-Personal-Public-strategic-prd'
                scriptType: 'pscore'
                scriptLocation: 'scriptPath'
                arguments: '"prd" "uksouth"'
                addSpnToEnvironment: true
                scriptPath: '$(Build.sourcesDirectory)/.azure-pipelines/scripts/SetSqlServerAdminCredentials.ps1'

            - task: AzureCLI@2
              displayName: CreateDatabaseAADGroups
              inputs:
                azureSubscription: 'spn-ado-Personal-Public-strategic-prd'
                scriptType: 'pscore'
                scriptLocation: 'scriptPath'
                arguments: '"prd"'
                addSpnToEnvironment: true
                scriptPath: '$(Build.sourcesDirectory)/.azure-pipelines/scripts/CreateDatabaseAADGroups.ps1'

  - deployment: DeployPrdPlatformBicep
    dependsOn: [DeployPrdPlatformKeyVaultBicep]
    environment: 'platform-strategic-services'

    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self
            
            - task: AzureCLI@2
              displayName: DeployPrdPlatformBicep
              inputs:
                azureSubscription: 'spn-ado-Personal-Public-strategic-prd'
                scriptType: 'pscore'
                scriptLocation: 'inlineScript'
                inlineScript: |
                  $sqlAdminOid = (az ad group show --group "sg-sql-platform-prd-admins" --query 'id')  | ConvertFrom-Json

                  az deployment sub create `
                    --template-file bicep/platform.bicep `
                    --location 'uksouth' `
                    --parameters @params/platform.prd.json `
                      parSqlAdminOid=$sqlAdminOid

  - job: DeployPrdPlatformPermissions
    dependsOn: [DeployPrdPlatformBicep]
    steps:
      - task: AzureCLI@2
        displayName: CreateSqlServerRoleAssignment
        inputs:
          azureSubscription: 'spn-ado-Personal-Public-strategic-prd'
          scriptType: 'pscore'
          scriptLocation: 'scriptPath'
          arguments: '"sql-platform-prd-uksouth" "rg-platform-sql-prd-uksouth"'
          scriptPath: '$(Build.sourcesDirectory)/.azure-pipelines/scripts/CreateSqlServerRoleAssignment.ps1'