trigger: none

pool: 'Dedicated'

resources:
  pipelines:
  - pipeline: dns-config-mgmt.Validate
    source: dns-config-mgmt.Validate
    trigger: true

stages: 
- stage: DeployPrdPlatform
  jobs:
  - job: DeployPrdPlatformBicep
    steps:
      - task: AzureCLI@2
        displayName: DeployPrdPlatformBicep
        inputs:
          azureSubscription: 'spn-ado-Personal-Public-strategic-prd'
          scriptType: 'pscore'
          scriptLocation: 'inlineScript'
          inlineScript: |
            az deployment sub create `
              --template-file bicep/platform.bicep `
              --location 'uksouth' `
              --parameters @params/platform.prd.json