parameters:
- name: skipBicepValidate
  type: boolean
  default: false

trigger:
  branches:
    include:
    - main
    - feature/*
    - dependabot/*

schedules:
  - cron: "0 3 * * 0"
    displayName: Weekly Build
    branches:
      include:
      - main

pool: 'Dedicated'

stages: 
- stage: ValidateBicep
  jobs: 
  - job: LintCode
    displayName: Lint Code
    steps:
      - script: |
          az bicep build --file bicep/platformKeyVault.bicep
          az bicep build --file bicep/platform.bicep
        name: LintBicepCode
        displayName: Run Bicep Linter

  - deployment: ValidateBicepCode
    dependsOn: [LintCode]
    environment: 'platform-strategic-services'

    strategy:
      runOnce:
        deploy:
          steps:
            - task: AzureCLI@2
              name: RunPreflightValidation
              inputs:
                azureSubscription: 'spn-ado-Personal-Public-strategic-prd'
                scriptType: 'pscore'
                scriptLocation: 'inlineScript'
                inlineScript: |
                  az deployment sub validate `
                    --template-file bicep/platformKeyVault.bicep `
                    --location 'uksouth' `
                    --parameters @params/platformKeyVault.prd.json

                  if ('${{ parameters.skipBicepValidate }}' -eq $false)
                  {
                    az deployment sub validate `
                      --template-file bicep/platform.bicep `
                      --location 'uksouth' `
                      --parameters @params/platform.prd.json `
                        parSqlAdminOid='00000000-0000-0000-0000-000000000000'
                  }

            - task: AzureCLI@2
              name: RunWhatIfDeploy
              inputs:
                azureSubscription: 'spn-ado-Personal-Public-strategic-prd'
                scriptType: 'pscore'
                scriptLocation: 'inlineScript'
                inlineScript: |
                  az deployment sub what-if `
                    --template-file bicep/platformKeyVault.bicep `
                    --location 'uksouth' `
                    --parameters @params/platformKeyVault.prd.json

                  if ('${{ parameters.skipBicepValidate }}' -eq $false)
                  {
                    az deployment sub what-if `
                      --template-file bicep/platform.bicep `
                      --location 'uksouth' `
                      --parameters @params/platform.prd.json `
                        parSqlAdminOid='00000000-0000-0000-0000-000000000000'
                  }

